### ISSUE TITLE
ActionView::Template Error (uninitialized constant Fae::VERSION)

### ISSUE THREAD

**Issue by tshedor** [wearefine/fae#139]
From #135

Re [Fae::VERSION](https://github.com/wearefine/fae/issues/135#issuecomment-235975295): the `ActionView::Template Error (uninitialized constant Fae::VERSION)` issue - I found a solution and didn't deep dive, although this issue needs to be properly resolved before considering Fae Rails 5-ready.

Set `config.eager_load` to `false` in `config/environments/production.rb`. Like I said, this will have to be revisited because we obviously want eager loading. Maybe requiring the gem for use in views?

**Comment by LeChin** [comment]
yes! this lets me log in, great workaround for now.

**Comment by jamesmk** [comment]
fixed by #177
