### ISSUE TITLE
Rail 5 and Kaminari issue - Activity Log Breaking

### ISSUE THREAD

**Issue by LeChin** [wearefine/fae#184]
Need to upgrade kaminari gem to resolve error.

http://stackoverflow.com/a/34437768/5261969

"Attempting to generate a URL from non-sanitized request parameters! An attacker can inject malicious data into the generated URL, such as changing the host. Whitelist and sanitize passed parameters to be secure."

**Comment by jamesmk** [comment]
fixed in v1.5!
