### ISSUE TITLE
Integration with existing Rails app

### ISSUE THREAD

**Issue by kinsomicrote** [wearefine/fae#208]
At the moment, is it possible to integrate Fae into an existing application?

**Comment by jamesmk** [comment]
@kinsomicrote It is possible as long as the Rails version is 4.1+.

If the objects you want to manage in Fae already exist it can be a bit awkward. Fae shines when you can utilize it's generators to build out the models, views and controllers for the admin. 

Check out the Quickstart Guide to see how they're used:  
https://www.faecms.com/documentation

If generators are not an option you can look at examples and follow the conventions the generator uses to manually build you admin controllers and views. Examples can be found in the dummy app:

https://github.com/wearefine/fae/blob/master/spec/dummy/app/models/release.rb
https://github.com/wearefine/fae/blob/master/spec/dummy/app/controllers/admin/releases_controller.rb
https://github.com/wearefine/fae/tree/master/spec/dummy/app/views/admin/releases

thanks!
