### ISSUE TITLE
has_and_belongs_to_many association between a StaticPage and an objects

### ISSUE THREAD

**Issue by cczeplak** [wearefine/fae#212]
Is there an easy way to create an association between a static page and a model?

Ex: I would like to select n People (Person model) on a about_us page.

**Comment by jamesmk** [comment]
Hi @cczeplak! There's no built-in way to do this in Fae, but Fae's easy enough to customize. For your use case I'd try the following:

Add the foreign key to `fae_static_pages` (the parent object of any static page)
```
add_column :fae_static_pages, :person_id, :integer
```

Define the association in the `AboutUsPage` model
```
belongs_to :person
```

Add the person selector to the static page form
```
= fae_pulldown f, :person
```

Hope this helps!
