### ISSUE TITLE
Install generator fails on running migrations with Rails 5.1

### ISSUE THREAD

**Issue by lilfaf** [wearefine/fae#217]
Running the install generator causes this error :

````
Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for: class AddUserTable < ActiveRecord::Migration[4.2]
````

This is due to Rails 5 major changes on the migration api :

https://github.com/rails/rails/blob/0c19d97939161b907bef6e33024def25f98eb361/activerecord/lib/active_record/migration.rb#L522

**Comment by jamesmk** [comment]
I've looked into this issue a bit and there isn't going to be an easy way to support Rails 4 and 5.1+ without writing our own migration copy method.

Currently Fae migrations live on the engine and get copied over on install with `rake fae:install:migration'`. If we start adding the version number to the migrations in Fae then Rails 4 apps will see `NoMethodError: undefined method `[]' for #<ActiveRecord::Migration:0x007f9ef2288c08>` next time they need to copy and run migrations.

I will report the issue to Rails and consider a manual copy method if it doesn't get attention before 5.1.0.

thanks

**Comment by jamesmk** [comment]
Doesn't look like we're getting much help from Rails: https://github.com/rails/rails/issues/28766

I'll need to update the way migrations are managed to support both Rails 4 and 5.1. In the meantime you can update the parent class in all the migrations Fae generates to be `ActiveRecord::Migration[4.2]`.

thanks

**Comment by lilfaf** [comment]
Alright ! The Clearance example is actually what I was thinking about. Devise does it the same way :
https://github.com/plataformatec/devise/blob/master/lib/generators/active_record/devise_generator.rb
Concerning the need for timestamping, file existance checking, etc, that you mentioned on the Rails issue, I guess `migration_template ` can handle that for you.

Regards

**Comment by jamesmk** [comment]
Thanks for the tip on `migration_template`, I'll look into that. I was thinking I'd just add the version to all migrations and have a second step strip it out on Rails 4 after `rake fae:install:migrations`. That way we can remove the second step once we drop Rails 4 support and be back to a clean system.

**Comment by cheesepaulo** [comment]
I change manualy ALL migrations to contains the version NameOfMigration < ActiveRecord::Migration**[5.0]**

And Works!

**Comment by jamesmk** [comment]
fixed in #396

**Comment by AntonAL** [comment]
I was having the same error.
On fae 2.0 after executing `rails g fae:install`, I've noticed, that copied migration files are without rails version number – `ActiveRecord::Migration`.
**Solution** – add version number to migrations manually.
Example: `ActiveRecord::Migration[5.2]`.

**Comment by dvergeylen** [comment]
Old topic but for anyone coming here from Google:
```
sed -i s/Migration$/Migration[4.2]/g db/migrate/*
```
will do the trick for you 😇
