### ISSUE TITLE
Page generator does not create page view

### ISSUE THREAD

**Issue by asecondwill** [wearefine/fae#219]
Just working through the Quick start...

running

````
rails g fae:page AboutUs hero_image:image hero_text:string introduction:text body:text annual_report:file
````

does not create the file
````app/views/fae/pages/about_us.html.slim````

And there is nowhere to admin pages in the /admin area.

**Comment by LeChin** [comment]
Hi @asecondwill!

Generated pages are created in the `app/views/admin/content_blocks` directory.

See docs for more details pertaining to generators: https://github.com/wearefine/fae/blob/master/docs/topics/generators.md#fae-page

**Comment by asecondwill** [comment]
https://www.faecms.com/documentation/topics-pages

think that needs updating then?

also, how do i get the admin area to show a link to edit the content block?

**Comment by LeChin** [comment]
@asecondwill good catch, feel free to open a PR with the fix!

> how do i get the admin area to show a link to edit the content block?

You will need to add a link in the `navigation_concern.rb` - see docs for example.
https://github.com/wearefine/fae/blob/master/docs/quickstart-guide.md#navigation

**Comment by asecondwill** [comment]
ok thanks.  i got there.   ill use the github docs from now.
