### ISSUE TITLE
Client View

### ISSUE THREAD

**Issue by nzraad** [wearefine/fae#226]
So, I am relatively new to Ruby on Rails, but I got everything setup and finished the Quickstart on FAE. Now, I am running into a problem of where exactly are the articles posting to? So, I assume it will be in the app/views/layout folder, since the admin folder is the actual admin interface. Can someone guide me into the next step of how to show my content to the client side? Thank you!

**Comment by jamesmk** [comment]
Welcome to Rails and Fae @nzraad! Please see my response to a similar issue: https://github.com/wearefine/fae/issues/218#issuecomment-294205097

If you are looking to get more help with Rails, http://guides.rubyonrails.org/ is a good place to start.

Good luck!
