### ISSUE TITLE
Support for image gallery form helper

### ISSUE THREAD

**Issue by foghina** [wearefine/fae#230]
I have a model ("article") that has an associated gallery of images. I've defined the relationship as:

```ruby
has_many :gallery_images, -> { where(attached_as: 'gallery_images') },
  as: :imageable,
  class_name: '::Fae::Image',
  dependent: :destroy
accepts_nested_attributes_for :gallery_images, allow_destroy: true
```

However, I can't find a way to add this to the associated form. I've tried:

```
= fae_image_form f, :gallery_images, attached_as: 'gallery_images', required: true
```

But that doesn't show up at all, and I can't see any errors in the log. Looking at [nested tables](https://www.faecms.com/documentation/helpers-partials#nested-table) and [nested forms](https://www.faecms.com/documentation/helpers-partials#nested-forms), it seems that I would need to create my own model on top of `Fae::Image` just to define the parent association, as I can't change `Fae::Image` itself.

But I'd like to avoid that and just have a form that handles uploading multiple images. Is there such a thing, and if not, how do I go about creating it?

**Comment by foghina** [comment]
Ok, I've tried adding the extra model, but I can't get that to work either. Here are my classes:

```ruby
class Article < ApplicationRecord
  include Fae::BaseModelConcern

  def fae_display_field
    title
  end

  has_fae_image :hero_image

  belongs_to :article_category
  has_many :article_photos

  accepts_nested_attributes_for :article_photos
end
```

```ruby
class ArticlePhoto < ApplicationRecord
  include Fae::BaseModelConcern

  belongs_to :article, touch: true

  def fae_nested_parent
    :article
  end

  def fae_display_field

  end

  has_fae_image :photo
  belongs_to :article
end
```

Then, in my `articles/_form.html.slim`, I have:

```
= render 'fae/shared/nested_table',
      assoc: :article_photos,
      parent_item: @item
```

This makes the form correctly show up when I click on 'Add Article photo'. However, when I go to save it, the photo is lost and the `ArticlePhoto` record is never created. I'm fairly new to Ruby and Rails, so perhaps I'm missing something really basic, but please help?

**Comment by foghina** [comment]
Also worth noting is that I don't see any errors / warnings in the server terminal, though it looks like the file was uploaded correctly:

```
Started PATCH "/admin/articles/1" for ::1 at 2017-04-22 19:31:01 +0100
Processing by Admin::ArticlesController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"O2PyHEF3hk/t8Q5li39V+PkhStGdziF9TDpNr59wXNeodSnjxzcR9ac3rY+wta5HB9ZqgUK/oODvWpeGEoK0yA==", "article"=>{"title"=>"Fae is fawesome", "slug"=>"fae-is-fawesome", "published(1i)"=>"2017", "published(2i)"=>"4", "published(3i)"=>"22", "body"=>"Fae **all** day.", "article_category_id"=>"1", "hero_image_attributes"=>{"asset_cache"=>"", "imageable_type"=>"Article", "attached_as"=>"hero_image", "alt"=>"deadmau5", "required"=>"false", "id"=>"5"}}, "article_photo"=>{"photo_attributes"=>{"asset"=>#<ActionDispatch::Http::UploadedFile:0x007f4a82dccfc0 @tempfile=#<Tempfile:/tmp/RackMultipart20170422-17496-zben1q.jpg>, @original_filename="20170113203936_1.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"article_photo[photo_attributes][asset]\"; filename=\"20170113203936_1.jpg\"\r\nContent-Type: image/jpeg\r\n">, "asset_cache"=>"", "imageable_type"=>"ArticlePhoto", "attached_as"=>"photo", "alt"=>"test", "required"=>"false"}, "article_id"=>"1"}, "commit"=>"Create Article photo", "id"=>"1"}
  Fae::User Load (0.2ms)  SELECT "fae_users".* FROM "fae_users" INNER JOIN "fae_roles" ON "fae_roles"."id" = "fae_users"."role_id" WHERE "fae_users"."active" = ? AND "fae_roles"."name" = ? ORDER BY "fae_users"."first_name" ASC, "fae_users"."last_name" ASC  [["active", true], ["name", "super admin"]]
  Fae::User Load (0.1ms)  SELECT  "fae_users".* FROM "fae_users" WHERE "fae_users"."id" = ? ORDER BY "fae_users"."first_name" ASC, "fae_users"."last_name" ASC LIMIT ?  [["id", 1], ["LIMIT", 1]]
  Fae::Option Load (0.1ms)  SELECT  "fae_options".* FROM "fae_options" ORDER BY "fae_options"."id" ASC LIMIT ?  [["LIMIT", 1]]
  Article Load (0.1ms)  SELECT  "articles".* FROM "articles" WHERE "articles"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  Fae::Role Load (0.1ms)  SELECT  "fae_roles".* FROM "fae_roles" WHERE "fae_roles"."id" = ? ORDER BY -position DESC LIMIT ?  [["id", 1], ["LIMIT", 1]]
   (0.0ms)  begin transaction
  Fae::Image Load (0.1ms)  SELECT  "fae_images".* FROM "fae_images" WHERE "fae_images"."imageable_id" = ? AND "fae_images"."imageable_type" = ? AND "fae_images"."attached_as" = ? LIMIT ?  [["imageable_id", 1], ["imageable_type", "Article"], ["attached_as", "hero_image"], ["LIMIT", 1]]
   (0.0ms)  commit transaction
Redirected to http://localhost:3000/admin/articles
Completed 302 Found in 9ms (ActiveRecord: 0.8ms)
```

**Comment by jamesmk** [comment]
You are correct, `fae_image_form` can't handle multiple image uploads automatically and a nested table is the way to go. Did you create `ArticlePhoto` with the nested scaffold generator (https://github.com/wearefine/fae/blob/master/docs/topics/generators.md#fae-nested-scaffold)? This will generate the correct controller and views for the nested table/form.

Also, see this similar issue: #214

thanks

**Comment by foghina** [comment]
Yes, I used:

```bash
$ rails g fae:nested_scaffold ArticlePhoto article:references photo:image --parent-model=Article
```

The similar issue doesn't help me much AFAICT.

**Comment by jamesmk** [comment]
That looks good. I bet the object is failing on commit for some reason. Can you look at the logs again? The output you posted above looks to be for the wrong request, look for...

```
Started POST "/admin/article_photos" for ...
```

I bet there's a rollback in there. You can add a `create` method in your `ArticlePhotoController` which will override the method it inherits and debug why the object's not saving. Or if you have an example app you can post that recreates the issue I can take a peek.

thanks

**Comment by foghina** [comment]
It never posts to `/admin/article_photos`. It posts to `/admin/articles` with the photos attributes nested in, see the `article_photo` param in the log above. I found this weird as well but just thought that this is probably how it should work.

Should the nested form be submitted via ajax? The `form_for` in `article_photos/_form.slim.html` doesn't actually generate a `<form>` when requested via js, so the parent article form is submitted instead.

I'm new to RoR so I'm probably doing something incredibly nooby. Thank you for the help so far, I'll try to post a sample app at some point unless you have any other ideas I could try.

**Comment by jasonfine** [comment]
if your indentation is off in the parent form, you might inadvertently be submitting the outer parent form instead of the nested one, hence why you're seeing a post to `/admin/articles`.

without seeing your app, this is only a guess, but make sure your nested_table is getting rendered outside/on the same level as the parent `= simple_form_for(['admin', @item]) do |f|`

**Comment by foghina** [comment]
That's probably it, and it would make sense. I'll try it later today.

**Comment by jasonfine** [comment]
typically, you'd see a set up like this:

```ruby
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_input f, :name, input_class: :slugger
    = fae_input f, :slug
    = fae_input f, :seo_title, helper_text: 'Suggested: Company Name | Keyword-driven description of the page section. Approx 65 characters.'

- if params[:action] == 'edit'
  section.content
    == render 'fae/shared/nested_table',
      header: 'People',
      ordered: true,
      assoc: :investments_people,
      parent_item: @item,
      cols: [{attr: :fae_display_field, title: 'Name'}]
```

**Comment by foghina** [comment]
Yep, this worked. Thanks!
