### ISSUE TITLE
Internationalization limitations

### ISSUE THREAD

**Issue by felipehespanhol** [wearefine/fae#240]
Hi!

I recently started using Fae in a new project and I'm missing some internationalization functionalities. In my project I needed to override the "set_locale" private method in Fae's ApplicationController to set the locale with the configured default locale in my rails app. Also there are many terms in the views that do not use I18n, like the links in application/_header partial.

**Comment by jamesmk** [comment]
Hi @felipehespanhol,

While we support managing content in multiple languages, i18n support in Fae's UI isn't on our roadmap. I'm tagging this as a "feature request" and we gladly accept PRs.

thanks

**Comment by johnnyshields** [comment]
@jamesmk just want to clarify you will accept a PR to fully internationalize all text in the Fae GUI if my team makes it? (My company operates dual english / japanese and I18n would be a big help... many staff don't speak english.)

**Comment by johnnyshields** [comment]
@jamesmk any comment here? Internationalization is relatively easy, I'm happy to do this for Fae 2.0

**Comment by jamesmk** [comment]
Static content in the interface has been converted to translation vars in #434. `set_locale` will be using browser preferences in #469. 

If you want to override `set_locale` you can do it in the `Fae::ApplicationControllerConcern`. See: https://github.com/wearefine/fae/blob/master/docs/topics/concerns.md

Currently the admin supports :en and :cs. If you'd like to add more I'd happily accept a PR!

thanks
