### ISSUE TITLE
fae_image association gets persisted regardless of validation in certain circumstances

### ISSUE THREAD

**Issue by y-chiasson** [wearefine/fae#257]
make sure you have rails 4.2.9 installed

```
gem uninstall rails # ( select All option)
gem uninstall railties # ( select All option)
gem install rails -v 4.2.9
# or any other way you know how to create a rails app with a specific version
```

you can paste this shell script into a file and execute it or paste it in the terminal:

```
rails _4.2.9_ new failing_image_example
cd failing_image_example
echo "gem 'fae-rails', '1.5.1'" >> ./Gemfile
echo "gem 'carrierwave'" >> ./Gemfile
bundle install
bundle exec rails g fae:install

rails g fae:scaffold Article title:string hero_image:image
rake db:migrate
rake fae:seed_db

cat <<EOF > ./app/models/article.rb
class Article < ActiveRecord::Base
  include Fae::BaseModelConcern

  has_fae_image :hero_image

  validate :hero_image_is_valid
  validate :title_is_valid

  def hero_image_is_valid
    return if hero_image.asset?
    errors.add(:"hero_image.asset", 'hero_image asset cannot be nil')
  end

  def title_is_valid
    return if title.include? 'this string'
    errors.add(:title, "title must include 'this string'")
  end

  def fae_display_field
    title
  end
end
EOF
```
#### STEP 1 create an admin:
1. rails server # start rails
2. go to http://localhost:3000/admin/articles/new
3. be redirected and create your admin
4. go back to http://localhost:3000/admin/articles/new

#### STEP 2 create an article with image
1. in title field input: `this string`
2. upload a picture
3. press Save (validation will pass)

#### STEP 3 upload a new image and fail a validation
1. go back to the edit page (admin/articles/1/edit)
2. DELETE THE IMAGE
3. add another image
4. in title field input: `a` (validation will fail with: title must include 'this string')
5. in title field input: `a this string`
6. press Save (record got saved without fae_image!)

go to the edit page (admin/articles/1/edit)
and the article will not have an image

For debugging, I followed these steps:

```
echo "gem 'pry-rails'" >> ./Gemfile
bundle install
bundler open fae-rails
```

I put binding.pry on the first line inside the Fae::BaseController#update method and repeated Steps 2 and 3. I inspect the params and the value of @image.hero_image.asset but I still can't tell what the problem is...

I was able to solve this by adding this code in the `Article` class:

```
class Article
  after_save :save_hero_image
  def save_hero_image
    hero_image.save if hero_image.asset?
  end
end
```

I am using Fae in a few projects and I would like to solve this problem at the Fae level rather then implementing this code in all my projects.

Please let me know if 1. you were able to reproduce and 2. if there is anything we can do to solve this.

Thanks

**Comment by jamesmk** [comment]
Thanks for the well laid out bug report! I am able to reproduce it on the `Person` object in the dummy when I add  something like your custom includes validation.

```
  def name_is_valid
    return if name.include? 'this string'
    errors.add(:name, "title must include 'this string'")
  end
```

The main issue seems to be file persistence in Carrierwave not playing nice with the nested attributes of `Fae::Image`. I tried a couple things to no avail and will keep looking into it.

One way you could get around the issue is support your validation with JS. It's the form's redisplay where the persistence is lost. Fae uses a Gem called Judge to automatically translate AR validations to JS, however custom validations need a corresponding JS rule to work. You can read more here: https://github.com/joecorcoran/judge#writing-your-own-eachvalidator

thanks

**Comment by y-chiasson** [comment]
@jamesmk Thank you so much for taking the time to dig into this!
I noticed that when Judge is working, the form doesn't get submitted, and this issue doesn't spring up. 

With custom validations however, Judge can't translate them and I ran into this issue. I will try out the method you told me for now.

Thanks again @jamesmk !

**Comment by Spone** [comment]
Keep an eye on the upcoming [ActiveStorage](https://github.com/rails/activestorage) (planned for Rails 5.2), it may replace Carrierwave and a refactoring could fix the issue?

**Comment by y-chiasson** [comment]
I just came across this in the Carrierwave documentation!
I think this may be part of the issue.

[making-uploads-work-across-form-redisplays](https://github.com/carrierwaveuploader/carrierwave#making-uploads-work-across-form-redisplays)
