### ISSUE TITLE
Use a public CI environment

### ISSUE THREAD

**Issue by 6temes** [wearefine/fae#262]
Currently the tests of this repository run in private Jenkins server that belongs to WeAreFine, so collaborators cannot see the results of the tests.

It could be a good idea to move the CI to a public service, such as CircleCI or TravisCI, that have free plans for Open Source projects.

**Comment by jamesmk** [comment]
Yeah, the current setup with Jenkins isn't ideal for a public project. The problem is our test suite is very complex, running on multiple Rails versions with the Appraisals gem. We had it working on TravisCI but had inconsistent and slow results. And soon we'll also have it running on multiple Ruby versions too.

I have internal initiative to make it better. In the meantime I don't mind jumping into PRs and letting people know which tests failed.

thanks

**Comment by tannakartikey** [comment]
Hello,

There are alternatives for Travis i.e. www.rultor.com
Or someone from the community can give a try to Travis on a fork and make
it work with stability.

If you are open for the options, rest can be worked out.

Making such improvement is easier for you as well the community. The
"internal initiative" option or letting people know what failed does not
sound good for an open source project.

**Comment by jamesmk** [comment]
Our build process is fairly complicated for Fae. Beyond running tests, we also deploy the built-in dummy app on certain branches for QA purposes. After looking into what it would take to make Jenkins test results visible to the public, we will explore other options.

1. We can run tests in Travis CI and have Travis call to Jenkins on success to finish the build.
2. Completely detach tests and dummy deploy and maintain them in separate systems.

Either way, I acknowledge that test results should be visible to everyone, so I will reopen this ticket and follow up.

thanks

**Comment by tannakartikey** [comment]
@jamesmk There are no doubts that you acknowledge it.
Thanks for reopening the issue. Let me know if I can help in any way.

**Comment by cpitkin** [comment]
UPDATE: We are working on adding Travis integration. Stay tuned!

**Comment by jamesmk** [comment]
@cpitkin Tests are passing on Travis, over to you to finalize deployments via Jenkins.

thanks
