### ISSUE TITLE
Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written fo

### ISSUE THREAD

**Issue by Ph0ny** [wearefine/fae#265]
Heads up:

Running rails g fae:install got me:

`rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateFaeRoles < ActiveRecord::Migration[4.2]
/vagrant/db/migrate/20170712130807_create_fae_roles.fae.rb:2:in `<top (required)>'
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateFaeRoles < ActiveRecord::Migration[4.2]
/vagrant/db/migrate/20170712130807_create_fae_roles.fae.rb:2:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
        rake  fae:seed_db
rake aborted!
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such table: fae_roles: DELETE FROM "fae_roles"
/vagrant/lib/tasks/fae_tasks.rake:4:in `block (2 levels) in <top (required)>'
SQLite3::SQLException: no such table: fae_roles
/vagrant/lib/tasks/fae_tasks.rake:4:in `block (2 levels) in <top (required)>'
Tasks: TOP => fae:seed_db
(See full trace by running task with --trace)`

Adding class CreateFaeRoles < ActiveRecord::Migration**[5.1]** in all migrations similar solved this. Dont know if it's a global issue tho, but for future reference.

**Comment by jamesmk** [comment]
This issue has already been reported here: #217. We are currently working on Rails 5.1 support, check out the issue for more context.

thanks!

**Comment by Ph0ny** [comment]
@jamesmk 

Alright, could not find it searching.

Thanks for a good product.
