### ISSUE TITLE
Documentation typos

### ISSUE THREAD

**Issue by mitramejia** [wearefine/fae#272]
1. See at https://www.faecms.com/documentation/quickstart-guide
I think it should be _**validates**_ instead of **_validated_**
![documentation___quickstart_guide___fae_cms_for_rails](https://user-images.githubusercontent.com/2616517/28237011-77702dfe-6903-11e7-9bbf-214bd8a7a5d2.jpg)

2. See at https://www.faecms.com/documentation/helpers-form_helpers
I think it should be _**is**_ instead of **it**
![documentation___form_helpers___fae_cms_for_rails2](https://user-images.githubusercontent.com/2616517/28237136-2cb2a492-6906-11e7-89b9-94e80d7a7e92.jpg)

**Comment by jamesmk** [comment]
Fixed in #274. Thanks @mitramejia and @Spone!
