### ISSUE TITLE
Compatibility with money-rails

### ISSUE THREAD

**Issue by Spone** [wearefine/fae#280]
I have a money field on my model, managed with the `money-rails` gem:

```ruby
class Product < ApplicationRecord
  include Fae::BaseModelConcern

  def fae_display_field
    name
  end

  acts_as_list add_new_at: :top
  default_scope { order(:position) }

  # Money
  monetize :price_cents, allow_nil: true
end
```

If I use the `fae_input` in my form, it works

    = fae_input f, :price

But I'd like to use `fae_suffix` instead (to display the currency symbol next to the input):

    = fae_suffix f, :price, suffix: 'EUR'

Now it breaks (`Fae::undefined method 'price' for #<Product:0x007f7e26ead3b8>`), because `fae_suffix` is checking [`is_attribute_or_association?`](https://github.com/wearefine/fae/blob/a5629f02dc1393bb86444ed669ce940705bc0a64/app/helpers/fae/form_helper.rb#L36), and `money-rails` does not create an attribute named `price`.

**Solution**

A simple fix is to declare the attribute manually on the model:

```ruby
class Product < ApplicationRecord
  # ...

  # Money
  attribute :price
  monetize :price_cents, allow_nil: true
end
```

Do you think there is a way to handle this in Fae, maybe by updating `is_attribute_or_association?`?

**Comment by jamesmk** [comment]
I think we may be able to deprecate `is_attribute_or_association?`. I'll take a look.

thanks

**Comment by jamesmk** [comment]
@Spone the fix for this is on master, let me know if it works.

**Comment by Spone** [comment]
@jamesmk the issue is fixed when using master, thanks! :+1:
