### ISSUE TITLE
Is there support for building a scaffold as view only?

### ISSUE THREAD

**Issue by arinhouck** [wearefine/fae#289]
For example, I have a contact form which stores inquiries and want to display the admin portal of Fae. However I am just curious, if there is an API existing maybe that I am looking over in documentation for making a view only scaffold or maybe being brainstormed about as feature. 

My alternative solution for now is to create a design that matches the backend for displaying the respective types as display only or disable all fields on edit form.

Thanks,
Arin

**Comment by jamesmk** [comment]
Hi @arinhouck. There is currently no generator for view-only scaffolding. We've had to copy view files from other sections from time to time but it's not ideal, so a view scaffold might be a good idea. 

In other cases, we've customize a view so much it stays from Fae markup standards. Documenting those standards better would be something that could help both use cases.

I'll leave this open and see what others think of this feature request.

thanks

**Comment by Spone** [comment]
I have the exact same use case :)

It's not ideal, but I ended up copy-pasting files (see below).

My main issue is that I can't remove the _Cancel_ / _Save_ buttons from the `show` view, and get proper breadcrumbs:

![image](https://user-images.githubusercontent.com/38524/29214742-c4091a08-7ea8-11e7-9b9e-b72341be770f.png)

### config/routes.rb

```ruby
Rails.application.routes.draw do
  namespace :admin do
    # ...
    resources :contacts
  end
  
  # ...
end
```

### app/models/concerns/fae/navigation_concern.rb

```ruby
module Fae
  module NavigationConcern
    extend ActiveSupport::Concern

    def structure
      [
        # ...
        item('Contacts', path: admin_contacts_path)
      ]
    end

  end
end
```

### app/controllers/admin/contacts_controller.rb

```ruby
module Admin
  class ContactsController < Fae::BaseController
    include Rails.application.helpers

    def show
      @contact = Contact.find(params.require(:id))
    end
  end
end
```

### app/views/admin/contacts/index.html.slim

```slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize, new_button: false

main.content
  table
    thead
      tr
        th E-mail
        th Name
        th Product
        th Message
        th Sent

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td = link_to item.email, admin_contact_path(item)
            td = link_to item.full_name, admin_contact_path(item)
            td = item.product&.name
            td = truncate item.message
            td = fae_datetime_format item.created_at
      - else
        tr: td colspan="2" No items found
```

### app/views/admin/contacts/show.html.slim
```slim
header.content-header.js-content-header
  == render 'fae/shared/form_header', header: @klass_name

article.content.contact
  h1 Contact

  h2 From
  
  - if @contact.full_name.present?
    p
      strong First name:
      =< @contact.first_name
      br
      strong Last name:
      =< @contact.last_name
    
  p
    strong E-mail:
    =< link_to @contact.email, "mailto:#{@contact.email}"
  
  - if @contact.phone.present?
    p
      strong Phone:
      =< link_to @contact.phone, "tel:#{@contact.phone}"

article.content.contact
  h2 Message
  
  - if @contact.product.present?
    p
      strong This customer contacted us from product page:
      =< @contact.product.name
    hr
  
  p= simple_format @contact.message

article.content.contact
  h2 Details
  
  p
    strong Sent:
    =< @contact.created_at
  
  - if @contact.ip_address.present?
    p
      strong IP address:
      =< @contact.ip_address
```

### app/assets/stylesheets/fae.scss

```scss
// ...

article.content {
  p {
    line-height: 1.6;
  }

  &.contact {
    h1 {
      margin-bottom: 30px;
    }
  }
}
```
