### ISSUE TITLE
Conflicting Controllers with Devise & Devise Token Auth causing unwanted actions to be called

### ISSUE THREAD

**Issue by arinhouck** [wearefine/fae#302]
When I added Fae to an existing project that had Devise + Devise Token Auth for JSON API. Upon my request to my Customer Devise model (mounted by devise_auth_token). All `before_actions` from Fae's controller are being called.

Any thoughts? Something to do with extending ApplicationController?

```
Started POST "/api/v1/customers/sign_in" for 127.0.0.1 at 2017-08-11 22:49:53 -0700
Processing by Overrides::SessionsController#create as JSON
  Parameters: {"customer"=>{"email"=>"arinhouck@gmail.com", "password"=>"[FILTERED]"}, "session"=>{"customer"=>{"email"=>"arinhouck@gmail.com", "password"=>"[FILTERED]"}}}
Can't verify CSRF token authenticity.
  Fae::User Load (0.8ms)  SELECT "fae_users".* FROM "fae_users" INNER JOIN "public"."fae_roles" ON "public"."fae_roles"."id" = "fae_users"."role_id" WHERE "fae_users"."active" = $1 AND "fae_roles"."name" = $2 ORDER BY "fae_users"."first_name" ASC, "fae_users"."last_name" ASC  [["active", "t"], ["name", "super admin"]]
Redirected to http://lvh.me:3000/admin/first_user
```

Ruby 2.3.1
Rails 5.0.5
Fae 1.5.1
Devise Auth Token 0.1.42
Devise 4.3.0

**Comment by jamesmk** [comment]
@arinhouck It'll be hard to see what's going on without more context. Is your project OS or could you recreate and share the issue in another project? 

thanks

**Comment by arinhouck** [comment]
@jamesmk I can label the project as public temporarily as it doesn't have any business logic built in yet. I just setup the basic structure with public facing API for Customers using Devise Auth Token with a multi-tenant database wrapping the Fae objects (Apartment). So each tenant has there own Fae Admin Portal.

However Apartment in this equation should not affect the outcome.
https://github.com/arinhouck/stuff2du

**Comment by arinhouck** [comment]
It wouldn't let me attach .json so I had to zip the file. Here is the request I am trying to make through Postman.

[Stuff2du Local.postman_collection.json.zip](https://github.com/wearefine/fae/files/1219879/Stuff2du.Local.postman_collection.json.zip)

**Comment by arinhouck** [comment]
I think it just clicked what I needed to do after sleeping on it and reading this repetitively. I fixed the issue by configuring `devise.rb` to inherit its parent controller as `ActionController::Base` instead of default ApplicationController.

```
  config.parent_controller = 'ActionController::Base'
```

However will I see any side-effects to this is the real question? Fae seems to be working and my devise token auth no longer calls Fae::ApplicationController actions.

**Comment by arinhouck** [comment]
New issue: Now my current issue is the views that are override through Fae are overriding my default Devise views.

**Comment by jamesmk** [comment]
@arinhouck Sounds like you've been on quite a journey, glad to see you're making progress.

I was afraid that your original issues wasn't going to be the only one to come up in this setup. I don't know off hand what it would take to make this edge case any easier to integration, but I'm open to suggestions or better yet, a PR. I'd consider this type of support a feature request.

If you managed to get this working with your custom setup, a brief doc in our tutorials section would be amazing!

thanks

**Comment by arinhouck** [comment]
@jamesmk 

Yeah, this issue exists in many different gems involved with Devise as there can only be one base controller of Devise. You can read more about the issue [here](https://github.com/plataformatec/devise/issues/2827). Put together a quick write up on #307

**Comment by jamesmk** [comment]
Thanks again for the tutorial @arinhouck. I'm closing this one out.
