### ISSUE TITLE
Authorization: prevent users from deleting objects

### ISSUE THREAD

**Issue by Spone** [wearefine/fae#304]
I'd like to prevent users with role `user` from deleting objects from the website (basically, CRUD without D). After reading the [documentation about authorization](https://www.faecms.com/documentation/features-authorization) it seems there is no built-in way of doing this.

Do you have ideas on how to implement this? I'm familiar with [Pundit](https://github.com/elabs/pundit), so I may try using this for more granular rights managament, but I wanted to check with you first, in case there is a simple way of doing it with Fae.

Thanks!

**Comment by jamesmk** [comment]
The authorization baked in only allows wholesale control of an object per role, but you should be able to roll something custom over it. 

If it's preventing a certain role from deleting anything, you might get away with a method on the `before_destroy` callback. If you want deeper control, you should be able to layer a gem like Pundit over.

If you need to adjust core Fae models there are concerns you can use that allow you to do so without having to override the entire model: https://github.com/wearefine/fae/blob/master/docs/topics/concerns.md

thanks
