### ISSUE TITLE
Documentation nav broken?

### ISSUE THREAD

**Issue by Spone** [wearefine/fae#311]
Hey there,

I think it's not the first time it happens, today the documentation nav is missing some sections:

![image](https://user-images.githubusercontent.com/38524/29407559-0bb23362-8345-11e7-8662-c86b23cb15a5.png)

Any idea what happened?

PS: also, can you remove the "fadeOut/fadeIn" transition effect? It makes navigation in the documentation needlessly laborious as it happens *after* the page is loaded (at least in Firefox on Ubuntu).

**Comment by jamesmk** [comment]
I fixed the navigation, which is a symptom of a larger API issue that still needs to be resolved. I'll also add your feedback to the doc to be looked at during the next sprint.

thanks

**Comment by jamesmk** [comment]
P.S. if you scroll down the [README](https://github.com/wearefine/fae), the same documentation can be found in GitHub form as well.

**Comment by Spone** [comment]
Yes I fell back to the documentation on Github, thanks!
