### ISSUE TITLE
devise_mailer_sender not taken into account

### ISSUE THREAD

**Issue by Spone** [wearefine/fae#312]
Hello,

I changed the value of `config.devise_mailer_sender` in `config/initializers/fae.rb` but it's not taken into account, maybe it's loaded too late on initialization (after `config/initializers/devise.rb`?)

I fixed it by copying `config/initializers/devise.rb` from Fae to my app, and changing the value of `mailer_sender` there.

Rails 5.1, Ruby 2.4.1

Do someone else have this issue?

**Comment by Spone** [comment]
By the way, I have the same issue with `config.per_page` which is not taken into account before I copy `config/initializers/kaminari_config.rb` into my project as well.

**Comment by jamesmk** [comment]
@Spone I updated #313 to resolve the Kaminari issue too
