### ISSUE TITLE
Add a link picker field

### ISSUE THREAD

**Issue by Spone** [wearefine/fae#315]
Hello,

this is a feature request. I'd like to allow my back-office users to select the link associated with a button on the front-end. To do that, I need Fae to be aware of the URLs and titles of my website pages.

It could work as a pulldown (see below)

![](https://raw.githubusercontent.com/wearefine/fae/master/docs/images/pulldown_search.gif)

which would display all the website pages (with their title), and maybe a way to preview the URL.

Then it would save the URL (or maybe only the path would make more sense) in a text field.

I was thinking that a way of doing that could be to have a `SiteMap` model, where the developer would build a list of all pages. Then Fae would use this model to populate the pulldown.

What do you think?

I'll be working on a first implementation, let me know if you have ideas.

**Comment by asecondwill** [comment]
Would this find just the static page links? or all pages with a path in the app? or just fae managed model records that have a path? I think the 3rd one would be ideal, so it has everything, without getting swamped.

**Comment by asecondwill** [comment]
if you save the path,  the link could be broken if the user changes the slug for a record later on.  Alternative might be a Link model, a bit like:

https://github.com/sheadawson/silverstripe-linkable/blob/master/code/dataobjects/Link.php


Which would allow for more flexibility and maybe a richer interface down the line.
