### ISSUE TITLE
fae_association not compatible with simple_form's include_blank

### ISSUE THREAD

**Issue by Spone** [wearefine/fae#316]
Hello,

I have a association pulldown which is optional. I passed the `include_blank: true` option to the helper, but I still have no way of "deselecting" a value.

Model:

```ruby
class PlanningDate < ApplicationRecord
  # ...
  belongs_to :spot, required: false
  # ...
end
```

Form:

```ruby
fae_association f, :spot, include_blank: true
```

I see that you use Chosen for these inputs. They have [a specific option](https://harvesthq.github.io/chosen/#allow-deselect-on-single-selects) for this: `allow_single_deselect: true`

Could you add this option when `include_blank: true` is passed?

**Comment by LeChin** [comment]
Hi @Spone,

If you pass in something to `include_blank`, you will be able to select that option.

Try: `fae_association f, :spot, include_blank: 'Select One'`

Hope that helps!

**Comment by Spone** [comment]
Nice one, but now I have twice "Select One" when I create a new record.

**Comment by LeChin** [comment]
Ah! You're right, we are looking into a fix for this, thank you.

**Comment by andrewdang17** [comment]
@Spone it looks like you can use `prompt: 'select one'` and it won't generate a duplicate. @jamesmk do you still want to maybe fix `include_blank` or should we just suggest using `prompt` in the documentation?

**Comment by jamesmk** [comment]
@Spone Fae uses the `prompt` option to add "Select One" by default which is the method to deselect an option. Is that not happening for you? You can override this message by passing in a custom `prompt` as @andrewdang17 suggested.

thanks

**Comment by Spone** [comment]
The "Select One" item is displayed when I'm creating a record:

![new](https://user-images.githubusercontent.com/38524/30826837-3f8bf4ae-a238-11e7-99f3-daa7733fe9eb.png)

but it disappears when I'm editing it, so I can no longer unselect:

![edit](https://user-images.githubusercontent.com/38524/30826909-7a8962da-a238-11e7-8275-e28158bf6bcb.png)

**Comment by Spone** [comment]
:+1: @andrewdang17
