### ISSUE TITLE
Anyone can create super user by direct post to first user endpoint

### ISSUE THREAD

**Issue by elct9620** [wearefine/fae#318]
We are using FAE 1.5.1 for our programmer language community official site. But when we try to create the first user, there are two admin open `/admin/first_user` and submit it.

In this case, we create two super admin but it should not happen if already have a super admin.

**Comment by jamesmk** [comment]
You are right, we protect displaying `/admin/first_user` when a super admin is present, but not the post endpoint. I will look into a fix.

thanks!
