### ISSUE TITLE
Best practice for displaying content pages

### ISSUE THREAD

**Issue by christophebeling** [wearefine/fae#327]
Hello, 

what is the best practice for displaying static content pages in the frontend? Should i create a own controller for every site i'm going to create or is there already some functionality like a dynamic frontend routing / content controller?

**Comment by jasonfine** [comment]
hi, this section sums it up pretty well:
https://www.faecms.com/documentation/topics-pages#getting-your-content-blocks

so no, no content controller or anything like that, it's up to you to set up the usage of the page/content blocks as you see fit.
