### ISSUE TITLE
Display image previews in a gallery 

### ISSUE THREAD

**Issue by mitramejia** [wearefine/fae#334]
After reading trough #230 I see we can add a gallery of images as a field. In my case the nested table does not show any preview or name. Im new to rails son maybe I'm missing something basic. 
How can I show a image preview and name like the single image form field does? Thank you for this awesome cms!

**Desired state**

![a_kid_s_party_express___edit_product_category](https://user-images.githubusercontent.com/2616517/31632502-98718c3c-b269-11e7-889b-1e5292793809.jpg)

**Current state**

![a_kid_s_party_express___edit_product](https://user-images.githubusercontent.com/2616517/31632492-8c568362-b269-11e7-9c30-7a2b49b511b6.jpg)

**Comment by tshedor** [comment]
Hey @mitramejia , you're actually really close. On that partial render (at the bottom of `admin/.../edit.html.slim` and the entirety of `admin/.../table.html.slim`) you can [add an option](https://github.com/wearefine/fae/blob/master/docs/helpers/partials.md#nested-table) for `has_thumb`.

If your model has additional properties or say multiple images and is not a pure `Fae::Image`, you can hack around the requirements of `has_thumb`.

```ruby
# models/gallery_image.rb
class GalleryImage < ApplicationRecord
  include Fae::Concerns::Models::Base
  has_fae_image :desktop_image
  has_fae_image :mobile_image

  def asset
    desktop_image.asset if desktop_image.present?
  end
end
```

```slim
/ views/admin/gallery_images/table.html.slim
== render 'fae/shared/nested_table',
  assoc: :gallery_images,
  parent_item: @parent_item,
  has_thumb: true,
  edit_column: true
```

**Comment by mitramejia** [comment]
Excellent @tshedor! adding `has_thumb` on `admin/.../edit.html.slim` and `admin/.../table.html.slim` did it. I see both files are tasked with rendering a `nested_table`. Out of couriosity, why do we need to edit both files to add the `has_thumb` option? there's a way to avoid editing both files?

**Comment by tshedor** [comment]
@mitramejia that's a good question. @jamesmk may be able to provide a more practical answer, but I'll give you a simple one: the `parent_item` association.

```slim
/ _form.html.slim
== render 'fae/shared/nested_table',
  assoc: :gallery_images,
  parent_item: @item,
  cols: [:name, :category, :live],
  ordered: true

/ table.html.slim
== render 'fae/shared/nested_table',
  assoc: :gallery_images,
  parent_item: @parent_item,
  cols: [:name, :category, :live],
  ordered: true
```

You could, theoretically, do something like (untested code below): 
```slim
/ _form.html.slim
== render 'admin/views/gallery_images/table'

/ table.html.slim
== render 'fae/shared/nested_table',
  assoc: :gallery_images,
  parent_item: @parent_item || @item,
  cols: [:name, :category, :live],
  ordered: true
```

**Comment by mitramejia** [comment]
Tested the code, rails can't find the template.

![action_controller__exception_caught](https://user-images.githubusercontent.com/2616517/31756141-c3f54416-b44e-11e7-9a3e-ce14880ecd47.jpg)

**Comment by tshedor** [comment]
@mitramejia Sorry about that. When I'm back to a Ruby day I'll give it a run.

**Comment by tshedor** [comment]
@mitramejia Got it. If you notice in the error output, rails is looking for a partial with a leading underscore (`_table`). You can get around this by specifying `file`:

```slim
== render file: 'admin/gallery_images/table
```

**Comment by mitramejia** [comment]
Excellent @tshedor now I see how it works
