### ISSUE TITLE
Consolidating form_header in v2.0

### ISSUE THREAD

**Issue by tshedor** [wearefine/fae#336]
@jamesmk Master of deletions here, proposing a deletion.

The current generator spits this out:

```slim
header.content-header.js-content-header
  == render 'fae/shared/form_header', header: @klass_name
== render 'fae/shared/errors'
```

This is in _a lot_ of files. Since this is a breaking version, I'd like to propose expanding the `form_header` partial to combine everything.

```slim
== render 'fae/shared/form_header', header: @klass_name
```

On content blocks, it'd look like this

```slim
== render 'fae/shared/form_header', header: @item, f: f, errors: false
```

**Cons**
Upgrading from v1.x to v2.0 will require manual remove of all `header.content-header.js-content-header`. 

Anyone using a customized `form_header` will have to add the wrapper `header.content-header.js-content-header` to their customized partial. Looking at you, J.

**Pros**
Should a redesign occur in the future, HTML in the form header will not be a concern because it is managed in the partial. The more in the partials the better. With partials, there's less concern for breaking changes and less need to maintain older HTML when a JS file is updated, when a CSS class is changed, when extra functionality needs to be added to the header and the HTML is in the way.

Two less lines per `_form.html.slim`.

**Comment by jamesmk** [comment]
I'm a fan of this 👍
