### ISSUE TITLE
Question: setting fae fields in test factories

### ISSUE THREAD

**Issue by christophebeling** [wearefine/fae#353]
Hey guys, 

i'm having a litte problem define factories for my static pages. My factory looks like this

`
FactoryBot.define do
  factory :home_page, class: :home_page do
    title 'Homepage'
    headline 'My Headline'
    association :hero_image,  factory: :fae_image
  end

end
`

I also copied the existing Fae::Image Factory in my project. When i'm running the test i always get an error "undefined method `hero_image='.  What am i doing wrong? Could you maybe provide a sample factory using content blocks? Would be great. Thank you :)

**Comment by jamesmk** [comment]
Associations on static pages are created dynamically based on hash defined in `fae_fields` via the `instance` method. The caveat is it doesn't lend itself to factories for testing. There are some examples of how we test them in the dummy app:

https://github.com/wearefine/fae/blob/master/spec/features/page_validations_spec.rb#L15
