### ISSUE TITLE
Use json_translate gem for translations

### ISSUE THREAD

**Issue by johnnyshields** [wearefine/fae#364]
Currently we need to define one attribute per locale on the model.

```ruby
    = fae_input f, :title_en
    = fae_input f, :title_ja
    = fae_input f, :title_ko
    = fae_input f, :title_fr
```

A much better way to do this is to use the  [json_translate gem](https://github.com/cfabianski/json_translate) which stores translations in a Postgres `jsonb` field like so:

```ruby
{ en: "My Title", ja: "タイトル", fr: "Mon titre" }
```

When you need to add a new locale you don't need to modify your entire application. Please consider this.

**Comment by jamesmk** [comment]
Thanks for the feature request. This is a non-backwards compatible change, but I'd consider this for a future major release. However 2.0 is coming out soon and there's no timeline for 3.0, so it would be a ways out.

thanks

**Comment by johnnyshields** [comment]
@jamesmk support could be added for this in a backwards compatible fashion as a new input type. This is my code:

```
    def fae_i18n_input(f, attr, options = {})
      locale_options = options.delete(:locale_options) || {}
      I18n.available_locales.map do |locale|
        fae_input f, "#{attr}_#{locale}", options.merge(locale_options[locale] || {})
      end.join.html_safe
    end
```
