### ISSUE TITLE
Feature Request: fae_datetimepicker

### ISSUE THREAD

**Issue by johnnyshields** [wearefine/fae#369]
Currently date picker doesn't allow you to pick a time. Would be nice if we could do this in one component. I'm currently working around this in two lines.

```
    = fae_datepicker f, :posted_at
    = fae_input f, :posted_at, as: :time
```

**Comment by jamesmk** [comment]
I would accept a PR on a new helper or additional option on the current helper. The current plugin we use doesn't have a great time integration and I don't want to add another plugin for this. In the past I've used standard inputs for datetime.

<img width="465" alt="screen shot 2017-12-21 at 9 43 09 am" src="https://user-images.githubusercontent.com/447575/34268017-fab77c00-e633-11e7-9159-13b2882df94b.png">
