### ISSUE TITLE
Feature Request: Built-in userstamps?

### ISSUE THREAD

**Issue by johnnyshields** [wearefine/fae#371]
Currently Fae tracks Changes, but doesn't add a userstamp (creator_id / updater_id) to the models being modified. Wondering if it makes sense to add something like  https://github.com/lowjoel/activerecord-userstamp into Fae.

**Comment by johnnyshields** [comment]
Would you accept a PR for this? I am thinking to add class method `has_fae_userstamp`

**Comment by jamesmk** [comment]
Thanks for the suggestion. Fae's change tracker associates users with each change. Adding something like userstamp to the models would be an easy addition outside of Fae and isn't a feature I think should be a default.
