### ISSUE TITLE
Improvement Request: Clone should direct to "new" form with fields pre-populated

### ISSUE THREAD

**Issue by johnnyshields** [wearefine/fae#373]
Currently the clone feature saves the cloned object to the database first then directs to the `edit` form.

Instead, it would be better if you directed to the `new` form with the fields pre-populated, without saving first.

**Comment by jamesmk** [comment]
We made the decision to create the record to allow cloning of associations dependent on an existing record. Creating it first makes our lives a whole lot easier.

thanks
