### ISSUE TITLE
Nested forms problems

### ISSUE THREAD

**Issue by cczeplak** [wearefine/fae#382]
I've two problems with nested forms:

1. When I save the nested form, there are two post requests and two records are created.

2. Is it possible to have images in nested forms. In my case the image in the nested form is created and after a reload of the page it is displayed in the nested table. But when I save the nested form with an image the form is not submitted via ajax.

Rails 5.1.4
fae 1.7

**Comment by Spone** [comment]
Same problem for me, after I updated Fae to 1.7

**Comment by jamesmk** [comment]
Thanks @cczeplak, we've recreated your first issue and are looking into it.

**Comment by jamesmk** [comment]
@cczeplak Yes, it's possible to have images in nested forms, you can see an example of that in the dummy app in the source. Releases have a nested table of aromas with and image included:

https://github.com/wearefine/fae/blob/master/spec/dummy/app/views/admin/releases/_form.html.slim
https://github.com/wearefine/fae/blob/master/spec/dummy/app/views/admin/aromas/_form.html.slim

thanks
