### ISSUE TITLE
Use existing User table instead of Fae::User

### ISSUE THREAD

**Issue by ChristinaGaitan** [wearefine/fae#386]
I’m working on an existing application that uses Devise our existing User class with Devise.  When I ran the installer, Fae generated another new class called Fae::User.  When I attempt to authenticate in using my existing paths, it has subverted my User class with it’s Fae::User class. Is there a way in which I can convince Fae to use my User table instead of Fae::User?

**Comment by justthisguy** [comment]
Fae seems great but this is a dealbreaker for anyone that is using Rails and Devise which is a very significant percentage of the community.  We cannot even evaluate it properly.

Perhaps this is really a feature request:  Fae should use the existing "User" model which is currently being used by Devise.

Please let us know where we go from here.

**Comment by jasonfine** [comment]
You can override/extend fae's models in the mounting app to make it use your existing setup. I have done this before on more than one occasion. e.g. create app/models/fae/user.rb in your app and tell it to use your existing users table, etc. you get the idea.

We did not have this scenario in mind when designing fae, it has always been intended to be in use from the conception of the application that's using it, and not tied into an existing/legacy system.

Perhaps this is something we could look into making easier down the road, and for now for your evaluation purposes you can start from a fresh app.

Thanks!

**Comment by bill-pairaktaridis** [comment]
> You can override/extend fae's models in the mounting app to make it use your existing setup. I have done this before on more than one occasion. e.g. create app/models/fae/user.rb in your app and tell it to use your existing users table, etc. you get the idea.

I'm sorry but could you elaborate on this? It seems that Fae doesn't really work without Devise. I can create a user but trying to login redirects `/sessions/user` which is not available on my app and I can only assume it's Devise related. Our app uses authentication via our API, so we don't even have a user's table, as you mention.

**Comment by jasonfine** [comment]
Ah yes, Fae is dependent on devise. Perhaps future plans will provide a means to not rely on it. 

Thanks

**Comment by bill-pairaktaridis** [comment]
I've gone ahead and attempted to implement Devise with an Admin model but that seems to come in conflict with `module Admin` in the controllers. Any suggestions?

**Comment by jasonfine** [comment]
Considering what was said in this comment https://github.com/wearefine/fae/issues/386#issuecomment-360612773, I would suggest generating a new app that uses Fae, and review what gets generated for it, and the overall setup in general to see how you would implement Fae into your existing application.
