### ISSUE TITLE
Improvement Request: Controller logic belongs in the Controller classes

### ISSUE THREAD

**Issue by johnnyshields** [wearefine/fae#388]
There are several methods like:
- `for_fae_index`
- `filter`
- `order_method`

Which are done in the model classes at the class-level. These methods belong in the Controller, not the Model. I strongly urge you to move them so that we may follow Rails best practices.

**Comment by jamesmk** [comment]
These three methods are all data concerns, so IMO they belongs in the model. `for_fae_index` and `filter` are essentially scopes which can be used across many controllers (and we do in our internally applications). 

thanks
