### ISSUE TITLE
Health check route

### ISSUE THREAD

**Issue by cpitkin** [wearefine/fae#389]
Add a route to allow for health checking without the need to render an entire page. This greatly helps with tools like Consul or load balancers that just need to know the application is alive. It would also reduce backend load since now database quires need to be made.

Route: `/health`, `/healthz`, `/status`, or `/heartbeat`
Method: GET
Returns: ` { "error": 0, "message": "ok"}` or `{"status": "ok"}`

**Comment by jamesmk** [comment]
I think we should keep Fae's concerns to managing content. IMO this would be a great feature in our template and starter kits.
