### ISSUE TITLE
Problems with new Page Attibutes

### ISSUE THREAD

**Issue by christophebeling** [wearefine/fae#391]
Hey guys, 

when working with fae on different instances with databases I ran into a small problem I'd like to discuss. 
I add an attribute to a Page-Object and start using it in a template on my local machine. Now I deploy this change to my staging/production environment and get an error once I open the frontend. Even though this will be fixed once I saved the new page in the backend once it seems pretty risky to me breaking production by deploying changes in the page objects. 

Right now I could think of to possible solutions: 
 - Creating a deployment task that saves all models to the database once. 
 - Changing Fae::StaticPage so it will not fail if there is no record in the database or even create an empty one on it's own. 

Any ideas on this?

**Comment by jamesmk** [comment]
Hey @christophebeling, can you give me a little more details on the error you're getting? An error message, stack trace and how you're calling `Fae::StaticPage` would be a good start.

In the documentation we encourage the use of `Fae::StaticPage#instance`, which as you suggested, creates a new record if one doesn't exist:
https://github.com/wearefine/fae/blob/master/app/models/fae/static_page.rb#L11

thanks

**Comment by christophebeling** [comment]
Hey @jamesmk, 
thanks for your fast reply. 

You are right, StaticPage creates a record if it dosen't exist. Still i'm getting an error when trying to access it's fae fields: 

When calling ``@item.myfield.content`` i get ``undefined method `content' for nil:NilClass``.

**Comment by tshedor** [comment]
@christophebeling have you tried `@item.myfield_content`?

**Comment by christophebeling** [comment]
Very good point. That fixes the issue for TextFields. Is there a similar method for savely accessing images?

**Comment by tshedor** [comment]
So if you've got `featured_image: { type: Fae::Image }` in the `self.fae_fields` method, you can get the URL via `PageModel.instance.featured_image.asset_url`. Personally, I don't like to live dangerously, so I print this like so:

```slim
# asset = PageModel.instance.featured_image
- if asset.present? && asset.asset_url.present?
  img src=asset.asset_url alt=asset.alt
```

**Comment by christophebeling** [comment]
Makes sense. Thank you man!
