### ISSUE TITLE
Widgets behavior

### ISSUE THREAD

**Issue by karensg** [wearefine/fae#392]
Hi guys,

It is great to see such a great CMS! In my opinion. it is the best out there at this moment.

Imagine, you would want to create different widgets, which consist out of different content blocks. These widgets would then be available to be added to the pages. Is there a way in Fae to create this behavior? How would you do that in Fae?

Karens

PS: btw, any ETA on v2? Would be awesome to start using 5.1

**Comment by jasonfine** [comment]
hey thanks for the kind words!

regarding the widget thing: there's no system in place in fae to do this "out of the box" but with rails being as flexible as it is, i think you could easily set up your own system using regular rails models and shared partials to achieve something like this. you could even do it with the fae page model and just call the page that represents the widget's `instance` method wherever you need to use it, but that seems like a misuse of the page model and i would take the regular models/partials approach.

**Comment by jamesmk** [comment]
I am picking v2 development back up. Included in that will be a feature that allows you to add content block groups to pages and objects. This will allow you to add different types of content blocks to a page directly from the admin, along with the ability to CRUD and order them.

I'm not sure if this meets your criteria, but Fae is built to be customizable. You could build a custom feature over it directly in your application. Or if you're looking to reuse content in different objects, you could create a `Widget` object with a set of attributes and an area to CRUD them. Then apply them to pages and objects with an association.

thanks
