### ISSUE TITLE
i18n locale values not working on Pages/Content Blocks

### ISSUE THREAD

**Issue by richardm90** [wearefine/fae#393]
I'm reviewing FAE as a replacement CMS for some existing sites but I'm struggling to get the the i18n implementation to work on anything other than the default_locale when using Pages and Content Blocks.

When I try i18n support on standard models it does return the correct text for the current locale it's just text for Pages and Content Blocks that I can't get to work. If I set my default locale to en and then navigate to a page such as mysite.com/fr the text is still the english value. I have verified that the i18n.locale value is set correctly.

I have two languages enabled en and fr. If I set I18n.default_locale to either of these locales then the correct text value is retrieved.

It feels as though there must be some config setting relating to Pages and Content Blocks that needs setting somewhere. I've read the Multiple Language Support section in the documentation many times but still can't can't find any clues.

I've tried this on fae 1.7.1 and 1.5.0 with the same results.

Does anyone have this working on Pages and Content Blocks? If so are you able to share a simple example?

- Richard

**Comment by jamesmk** [comment]
Hi @richardm90, thanks for checking out Fae and sorry for the delayed response. 

Fae's main concern is managing you data, leaving the frontend implementations fairly loose. As far as getting the data to render on the frontend, there isn't a standard "Fae" method. 

I'm sure you've seen the method we provide to help you define and manage data in multiple languages. For pages, this is the `languages` key in the `fae_fields` hash. This will only define attributes for you to use. 

The following will give you access to `body_en_content` and `body_fr_content` attributes on your page.

```ruby
body: {
  type: Fae::TextField,
  languages: [:en, :fr]
}
```

From there you can setup a method that uses the `I18n.locale` to read the corresponding attribute on the frontend.

Hope this helps!

**Comment by richardm90** [comment]
Hi @jamesmk,

The admin features of fae are working as expected and allow :en and :fr versions of the fields to be maintained. It is on the frontend that I'm struggling but only for Pages and Content Blocks.

Could you clarify a point for me?

From a rails console I can do the following ...
$ item = AboutPage.instance

$ item.body_en.content
# returns the text I maintained for the :en locale

$ item.body_fr.content
# returns the text I maintained for the :fr locale

$ item.body.content
# returns the text I maintained for the I18n.default_locale

Is this expected behaviour? I was expecting this to return the text I maintained for the I18n.locale.

Richard

**Comment by jamesmk** [comment]
Correct, `item.body.content` is just an alias to the default locale. Those association are cached in the classes for performance reasons, so they can't change session to session. You can create a method to read `I18n.locale` and call the correct association.

Here's the basics, but you can write a helper or instance method to clean up the implementation:
```
item.send("body_#{I18n.locale}").content
```

**Comment by richardm90** [comment]
Thanks @jamesmk.

What did confuse me was the documentation which says ...

> The attribute can then be retrieved normally (i.e. `@item.name` will render `@item.name_en` if `I18n.locale` is `:en`).

However, that being said I just have found that if I include `translate :body` in my StaticPage model this does what I expected and @item.body will then return the I18n.locale value.

I was probably being a bit literal when reading the documentation and didn't appreciate that `translate` could be used for StaticPage models.
