### ISSUE TITLE
NoMethodError (undefined method `get' for ActiveModel::Errors)

### ISSUE THREAD

**Issue by andlrb** [wearefine/fae#400]
Hello!

I'm trying fae in an existing project and I'm encountering this error whenever I try to update a user, I've also encountered it when I try to add users while in development mode.

```
method=GET path=/admin/users/1/edit format=html controller=Fae::UsersController action=edit status=200
method=GET path=/admin/judge/ format=json controller=Judge::ValidationsController action=build status=500 error='NoMethodError: undefined method `get' for #<ActiveModel::Errors:0x00007f4fa8c498f8>

NoMethodError - undefined method `get' for #<ActiveModel::Errors:0x00007f4fa8c498f8>
```

Any ideas how I could debug this?

**Comment by jamesmk** [comment]
This is a Rails 5.1+ issue on a Fae dependency. The issue was resolved with https://github.com/joecorcoran/judge/pull/82. I'm working to get a new version of Judge release and included in Fae v2. Fae v2 should be released next week and will include Rails 5.1 and 5.2 support.

**Comment by andlrb** [comment]
Awesome, I can wait until then! 
Thanks so much for all the great work, I love Fae so far!

**Comment by jamesmk** [comment]
Fae 2.0 has been released with a fix for this.
