### ISSUE TITLE
User settings customization

### ISSUE THREAD

**Issue by mbajur** [wearefine/fae#414]
Hello,

i need to add several fields to user model and make it able for user to modify his profile. Like Bio and stuff like that.

Is it possible to customize Profile settings form in fae?

Thanks in advance

**Comment by jamesmk** [comment]
Yep! You can add a migration with the additional attributes on `Fae::User`. For amendments to the `Fae::User` model you can utilize a built in concern we added. See: https://github.com/wearefine/fae/blob/master/docs/topics/concerns.md

Or if you prefer you can just override the entire model by placing a file in you app at `app/models/fae/user.rb`. Similarly, you can override the controller (https://github.com/wearefine/fae/blob/master/app/controllers/fae/users_controller.rb) and views (https://github.com/wearefine/fae/tree/master/app/views/fae/users) as necessary. 

It's best to start with the original files in you app as a base and customize from there. The caveat is you won't be able to inherit updates to those files in future versions.

thanks

**Comment by mbajur** [comment]
Thank you! It indeed works as expected. I just have an issue with `fae_image_form`.

My user concern:

```
module Fae
  module UserConcern
    extend ActiveSupport::Concern

    included do
      has_fae_image :avatar
      has_fae_image :cover_photo
    end
  end
end
```

And in overwritten user form:
```
= fae_image_form f, :avatar, show_alt: false
= fae_image_form f, :cover_photo, show_alt: false
```

The problem is i can't see these two fields in the form. They are just not getting rendered. Have i misunderstood something here?

**Comment by mbajur** [comment]
Update:

i was able to make the inputs visible by rewriting `users_controller` and  adding

```
@user.build_cover_photo if @user.cover_photo.blank?
@user.build_avatar if @user.avatar.blank?
```

in the edit method btu really weird thing is happening - when my avatar/cover_photo is empty, i can see a browser-default file input. When i upload something and hit "Save", page reloads and i can see the stylised fileinputer inputs with image preview. Also, delete image button works and sends a request but the input is not getting updated. It updates after a page reload but not "live".

Any ideas on how to bind `fae_image_form` properly on that form ?
