### ISSUE TITLE
Documentation bug - Getting Content Blocks

### ISSUE THREAD

**Issue by harimohanraj89** [wearefine/fae#431]
Hello! 

I noticed in the "Getting Content Blocks" section of the "Pages and Content Blocks" documentation ([closest anchor link](https://www.faecms.com/documentation/topics-pages#adding-content-blocks)), alt text and caption for images is being accessed through the `asset` object.

<img width="1025" alt="screen shot 2018-10-02 at 10 56 05 am" src="https://user-images.githubusercontent.com/4241399/46330817-819cc700-c632-11e8-9e7c-cb0c362c9cfe.png">

I think this is incorrect, as I am unable to access those data points through the `asset` object (looks like this is the image uploader), but I _can_ access them through the field (`Fae::Image` object) directly, like so:

```ruby
@page.hero_image.alt
@page.hero_image.caption
```

I am using `fae-rails v2.0.0`.

Is the documentation incorrect? If so, I'd be more than happy to open up a PR to update.

PS: Looks like the "Getting Content Blocks" doesn't have an entry in the table of contents on that page either. I'd be glad to add that in as well while I'm in here.

**Comment by jamesmk** [comment]
@harimohanraj89 The documentation is incorrect, thanks for finding that! If you want to fix it in a PR, let me know. Otherwise I'll fix it in a couple days.

thanks!

**Comment by harimohanraj89** [comment]
Thank you! I have opened #480 to address!
