### ISSUE TITLE
How to use i18n to translate view template

### ISSUE THREAD

**Issue by chaucerling** [wearefine/fae#435]
examles: user forget_passowrd page, admin header dropdown

**Comment by xprazak2** [comment]
Hi, I have already opened #434 which uses I18n for translations. I would be grateful if anyone could test/review to confirm it works properly.

If you need an urgent solution, I suppose overriding the templates with added `t('translation.key')` could work, but I think it would be nice if fae supported translated admin interface.

**Comment by jamesmk** [comment]
The Fae interface now supports I18n, thanks to #434. Currently only en and cs are support, but others via PR would be appreciated!

thanks
