### ISSUE TITLE
Slug in the website

### ISSUE THREAD

**Issue by asecondwill** [wearefine/fae#443]
Sorry for this question:  What needs doing to use the slug that is being stored for my model - "Category" ?

Do I need to set up the to_param and finders myself? It isn't done in the Fae concerns?

I have it working by: 

```
#category.rb
def to_param
    slug
  end
```

```
#categories_controller.rb
def show    
    @category = Category.find_by(slug: params[:id])
  end
```

Which is simple enough, just wondering if its built in and I'm doubling it up?

**Comment by jasonfine** [comment]
is this in an admin or public facing controller?

**Comment by jasonfine** [comment]
regardless, ill say this: if it's an admin controller, i wouldn't mess with trying to use slugs in place of FAE's ID based routing - if that's your intention, it's definitely possible but you're on your own there.

in a public context i'd use a slug like this:

```
#routes
get 'categories/:slug' => 'categories#detail', as: :category_detail

#controller
def detail
  @category = Category.detail(params[:slug])
end

#model
class << self
  def detail(slug)
    where(slug: slug).first
  end
end
```

**Comment by asecondwill** [comment]
No not in admin.  Although I can see why you thought it might be as my above code broke the admin.  doh!

With your code there,  I had need to change the view to 

`category_detail_path(category.slug)`

to have the slug in the url.

Which is ok I guess.  Thanks for the comments.  Ill close.
