### ISSUE TITLE
Use devise to Authenticate Site Customers 

### ISSUE THREAD

**Issue by asecondwill** [wearefine/fae#446]
I want to add a Customer model for the users of my site to register / login.  They shouldn't have access to fae. Devise screens should be different to Fae users screens.

I thought I might be able to do it like I have for previous custom setups, more or less as the Devise wiki says

https://github.com/plataformatec/devise/wiki/How-to-Setup-Multiple-Devise-User-Models

But I get error

```
app/views/devise/sessions/new.html.slim
undefined method `customer_session_path'
```

This seems like the opposite of the setup in the Fae docs, 
https://www.faecms.com/documentation/tutorials-existing_devise

How can I keep Devise for Customers falling foul of the Fae devise setup?

**Comment by jasonfine** [comment]
Seems like if you generated/used scoped devise views, this path would have /customers/ in it somewhere like
`app/views/devise/customers/sessions/new.html.slim` 

As well after you have configured your customer devise routes, do you see anything when you
`rake routes` ?

**Comment by jasonfine** [comment]
PS this is a total shot in the dark, I've never used FAE like this.

**Comment by asecondwill** [comment]
I get customer routes in my rake routes output

```
cct git:master ❯ rake routes                                                                                                                                                                           ✹ ✭
Running via Spring preloader in process 32470
                      Prefix Verb   URI Pattern                                                                              Controller#Action
        new_customer_session GET    /customers/sign_in(.:format)                                                             devise/sessions#new
            customer_session POST   /customers/sign_in(.:format)                                                             devise/sessions#create
    destroy_customer_session DELETE /customers/sign_out(.:format)                                                            devise/sessions#destroy
       new_customer_password GET    /customers/password/new(.:format)                                                        devise/passwords#new
      edit_customer_password GET    /customers/password/edit(.:format)                                                       devise/passwords#edit
           customer_password PATCH  /customers/password(.:format)                                                            devise/passwords#update
                             PUT    /customers/password(.:format)                                                            devise/passwords#update
                             POST   /customers/password(.:format)                                                            devise/passwords#create
cancel_customer_registration GET    /customers/cancel(.:format)                                                              devise/registrations#cancel
   new_customer_registration GET    /customers/sign_up(.:format)                                                             devise/registrations#new
  edit_customer_registration GET    /customers/edit(.:format)                                                                devise/registrations#edit
       customer_registration PATCH  /customers(.:format)                                                                     devise/registrations#update
                             PUT    /customers(.:format)                                                                     devise/registrations#update
                             DELETE /customers(.:format)                                                                     devise/registrations#destroy
                             POST   /customers(.:format)                                                                     devise/registrations#create
```

..etc

**Comment by asecondwill** [comment]
I worked on this a bit more yesterday and went further down a rabbit hole of trying to unravel fae & devise for my front end.  

Am I doing this all wrong? Is it more normal just to use the Fae::User table for site users and just not grant them admin area permissions?  

Most sites I am likely to build with Fae are probably going to have a user login area so figuring out a nice simple way to do that with devise seems worth while.

**Comment by jasonfine** [comment]
I apologize as I am a bit backed up with client work at the moment to set up a use case for this locally, but did you try the method in fae docs for doing a setup like this? If you did and it's not working please let me know. Above it looks like you only tried doing it as devise docs say to.

**Comment by asecondwill** [comment]
No, I didn't use the method in the docs, as I'm happy to keep the Fae::users for admin login, and just regular devise for user login.

**Comment by asecondwill** [comment]
I thought it would be better to try to fit in with Fae, So I have switched to trying to just add a customer role and use the Fae::User model - but that seems blocked too.  For eg, I can't assign roles other than the standard ones to a user in the admin interface.

**Comment by asecondwill** [comment]
I started again today using the method in Fae docs.  I had completely misunderstood what they were doing.  They aren't replacing the fae::user admin auth, they are as well as, so exactly what I needed.  A few bits were missing but got me 90% of the way. Sorry to bother you.

**Comment by jasonfine** [comment]
No worries, glad you got it worked out!
