### ISSUE TITLE
Multiple Language Support Documentation

### ISSUE THREAD

**Issue by richardmoulton** [wearefine/fae#447]
A minor one but the documentation for the Displaying the Language Nav section talks about adding language: true to the  form_header partial but it should be languages: true.

It took me a while to realise this.

**Comment by Shigawire** [comment]
I've submitted a PR for the same issue: https://github.com/wearefine/fae/pull/444 

However, there hasn't been much activity recently.

**Comment by richardmoulton** [comment]
OK, cool, I'll close this issue then.
