### ISSUE TITLE
Redirection from new entity to edit said entity

### ISSUE THREAD

**Issue by Dasher83** [wearefine/fae#449]
Hi guys,

I've been using Fae for a couple of months now. I wonder if there is any way to edit an entity right after you create it through the new form. I tried to do this manually with some javascript redirection only to realize I could not capture the object ID since it is yet to be created. Fae uses an edition url based on the pattern : "/admin/entity/id", so I am at a bit of a loss here. Any reference would be helpful, thank you

**Comment by jasonfine** [comment]
You can override anything in fae. To do this you would add a custom `create` method to the controller for the object you want this to happen with, and in that method make it redirect to the edit path for the object instead of index.

**Comment by jasonfine** [comment]
Also helpful to reference fae's defaults in cases like this so you can

`bundle open fae-rails` on the cli and look at base_controller.rb

**Comment by jamesmk** [comment]
Piggybacking off of what @jasonfine  said, here's and example of what you can throw in your object controller to override the `create` method:

```
def create
  return create_from_existing(params[:from_existing]) if params[:from_existing].present?

  @item = @klass.new(item_params)

  if @item.save
    redirect_to edit_admin_entities_path(@item.id), notice: t('fae.save_notice')
  else
    build_assets
    flash[:alert] = t('fae.save_error')
    render action: 'new'
  end
end
```

The only line that varies from `Fae::BaseController` being:

```
redirect_to edit_admin_entities_path(@item.id), notice: t('fae.save_notice')
```

**Comment by Dasher83** [comment]
Thank you both very much for your help!
