### ISSUE TITLE
Could not find generator error on fae:install

### ISSUE THREAD

**Issue by amielouise2** [wearefine/fae#450]
I have a very simple rails app that's just static pages right now.  I've added the fae gem and the required sass gems to my gemfile.  Everything bundles fine but when I run `rails g fae:install` I get an error back
Could not find generator 'fae:install'

Rails version: 5.2.1.1
Ruby version 2.5.3

**Comment by jclemans** [comment]
What directory are you in when you run the generator?

**Comment by amielouise2** [comment]
the same directory as my app.  Is that not correct?

**Comment by jclemans** [comment]
Sounds like you're in the right spot. If you do `bundle show fae-rails` does it show the gem installed?

**Comment by victorhazbun** [comment]
This is happening to me as well.
