### ISSUE TITLE
Index data sorter for user defined association

### ISSUE THREAD

**Issue by Dasher83** [wearefine/fae#451]
Hi, in the documentation there is a way to make pagination and column sorting work together by using individual "data-sort" options in each column we want to sort in the index view of a fae model. It even lets you do the same with a defined association within the object you are sorting. All good until there. Now what I tried is to adapt this to a "has many association", by defining a static method in the model that returns a processed string. However, this breaks the pagination, from making it disappear to eliminate a page. I guess the bottom line is how to show and sort in index a user defined association. Here is my code:

//index.html.slim for post entity

== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content

 == fae_filter_form do
   == fae_filter_select :post

 table
   thead
     tr
       th data-sort="title" Title
       th.action-wide data-sort="departments" Departments
       th.action-wide data-sort="post_categories.name" Categories
       th.-action-wide data-sort="active" data-sorter="false" Active
       th.-action-wide data-sort="featured" data-sorter="false" Featured
       th.-action-wide data-sort="updated_at" Modified
       th.-action data-sorter="false"

   tbody
     - if @items.present?
       - @items.each do |item|
         tr id=fae_sort_id(item)
           td = link_to item.fae_display_field, edit_admin_post_path(item)
           td = item.departments
           td = Post.my_categories(item.id)
           td = fae_toggle item, :active
           td = fae_toggle item, :featured
           td = fae_date_format item.updated_at
           td = fae_delete_button item
     - else
       tr: td colspan="4" No items found

 == fae_paginate @items

//Static method in my Post model

def self.my_categories(post_id)
   categories = PostCategory.select('name').where("post_id="+post_id.to_s)
   categories_text = ""
   categories.each do |item|
     categories_text = categories_text+','+item.name
   end
   categories_text[1..-1]
end

**Comment by jasonfine** [comment]
Does a post belongs_to post_category?

**Comment by Dasher83** [comment]
No, it's the other way around. Many post_category belong to a post

**Comment by jasonfine** [comment]
Ah ok, the means to sort on association is meant for belongs_to situation. You are seeing odd behavior because of the way AR treats associated model inclusion via `includes`. If you are inclined you can look in the fae source to see how this works in `sortable.rb`, and perhaps come up with something custom for your use case.

Thanks
