### ISSUE TITLE
Multi Langage support for nested forms

### ISSUE THREAD

**Issue by kgeoir** [wearefine/fae#454]
Hello,
  I have a static page with a dynamic relation to an other model like in the doc:https://www.faecms.com/documentation/tutorials-dynamic_relationships_to_pages. Since my site is suporting multi-lange I did add the    fae_translate :title, :content in my model and happily it has all the fields but it seems that the partial  fae/shared/nested_table does not support weel the feature since it display localized fields and not just one input:
<img width="610" alt="screenshot 2019-03-03 at 16 54 34" src="https://user-images.githubusercontent.com/1089725/53697772-115ac300-3dd5-11e9-9b72-7bcd88fcabcf.png">

I was more expecting one field to be display. I looked in doc and in code it does not seems that this is supported. Did I miss something? Should I make a feature request?

Thank you!

**Comment by kgeoir** [comment]
So I found a workaround but it has over head:
In the form template loaded with an ajax call, I simply added Fae.navigation.languauge.init(); This way the JS function in charge of hiding other languages fields is passing by.
Unfortunatly if I click twice on the edit toggle btn, it switch to an other language...
I am not sure why... I ll continue to investigate and let you know meanwhile, if you have doc/ideas about it, it would be much appreciated!

**Comment by jamesmk** [comment]
Thanks for the bug report, this is a use case we haven't tested for. The display conditionals are applied on page load and toggle update. It doesn't take into account ajax loaded content.

It should be as easy as calling this after ajax complete on the form pages:
```
var language = $('#js-language').find('option[selected]').val();
Fae.navigation.language._toggleLanguageFields(language, 0);
```

But a use case in the dummy and some tests would be nice as well.

thanks
