### ISSUE TITLE
Please include the version number in the generator

### ISSUE THREAD

**Issue by baash05** [wearefine/fae#456]
For some reason the generator isn't adding the version number to the migrations.  They fall down. 

ActiveRecord::Migration[4.2] ?? Missing..

Workaround:
If you add the version manually then rerun the generator it works.

**Comment by jclemans** [comment]
Is this for the migration files that you get after installing Fae, or after generating/scaffolding a new model? I just did an install of Fae on Friday and the migration versions were included in those. What are the steps you did leading up to seeing this issue?
