### ISSUE TITLE
Nested forms don't seem to support wysiwyg fields

### ISSUE THREAD

**Issue by mooreds** [wearefine/fae#458]
I created a nested form according to the instructions: https://www.faecms.com/documentation/helpers-partials#nested-forms

Here's my form:

```
= simple_form_for(['admin', @item], html: {multipart: true, novalidate: true, class: 'js-file-form'}, remote: true, data: {type: "html"}) do |f|
  = fae_input f, :score
  = fae_input f, :description, html: true

  = f.hidden_field :question_id

  = f.submit
  = button_tag 'Cancel', type: 'button', class: 'js-cancel-nested cancel-nested-button'
```

The description field isn't rendering as html. I have another description field (on a model that is not nested) that is rendering the wysiwyg field just fine.

```
= simple_form_for(['admin', @item]) do |f|
  == render 'fae/shared/form_header', header: @klass_name

  main.content
    = fae_input f, :name
    = fae_input f, :allow_more_than_one_answer
    = fae_input f, :description, html: true
    = fae_association f, :change_model_area
```

Is there something I need to do to enable the wysiwyg field on the nested form?

**Comment by jasonfine** [comment]
No I think `Fae.form.text.init()` isn't getting called when the nested forms are loaded in `_ajax.js`, and that's what sets up the wysiwyg on a field.

**Comment by mooreds** [comment]
Any hints on where to call it? Is this the right js file to override or is there a better place? https://github.com/wearefine/fae/blob/master/app/assets/javascripts/fae/form/_ajax.js

**Comment by jasonfine** [comment]
Sorry I wasn't more clear, I am out for the next 2 days but can do this on monday, or you could submit a PR if this is urgent. This should be fixed/ happening in the fae core and not an overridden file.

**Comment by mooreds** [comment]
OK, happy to wait for a few days. Thanks for letting me know!

**Comment by fmoulton** [comment]
Hi @jasonfine - is there a status of this for us? Thank you for taking the time to add this 😄

**Comment by jasonfine** [comment]
https://github.com/wearefine/fae/pull/460
