### ISSUE TITLE
Allow update to Devise 4.6.2

### ISSUE THREAD

**Issue by Spone** [wearefine/fae#462]
I would like to be able to update Devise to 4.6.2, since there is a security issue in earlier versions, see https://github.com/plataformatec/devise/issues/4981

Why is there dependency to Devise `~> 4.4.3` and not `>= 4.4.3`?

**Comment by mooreds** [comment]
I think you meant 4.6.2, right @Spone ?

**Comment by Spone** [comment]
You're right @mooreds :)

**Comment by mooreds** [comment]
Ping

**Comment by baash05** [comment]
The 1.7.1 version of the gem allows for the updated devise. I uses a >= not the ~.
I've locked my version for now.

**Comment by jamesmk** [comment]
@Spone We are locking major dependencies to minor versions to avoid inconsistent functionality. I've opened a PR to bump the version of Devise in v2.1. You can wait until v2.1 is released or point directly to the v2.1 branch in you gemfile (although this branch is in active development).

thanks!
