### ISSUE TITLE
Import data

### ISSUE THREAD

**Issue by EdSF** [wearefine/fae#467]
Unsure if this is the correct forum for such, otherwise, I'll delete.

Curious to know if you have any recommendations for importing existing data into FAE - perhaps in the seed process? 

IMHO, it would be great for migration use cases (e.g. Wordpress). 

Thanks ~

**Comment by jclemans** [comment]
You definitely can. I regularly use a custom rake task to read from spreadsheets to run the scaffold generators in order to build out new object models or static pages faster. You could certainly do something similar to save new attribute data or associations to existing models you have set up.

**Comment by EdSF** [comment]
> You definitely can. I regularly use a custom rake task to read from spreadsheets to run the scaffold generators in order to build out new object models or static pages faster. You could certainly do something similar to save new attribute data or associations to existing models you have set up.

Thank you for confirming that - that gives me enough to go tinker with. Am not even a n00b - currently just perusing guides/docs to grok things and one of the reqs is migrating data (i/o) where the immediate task is importing.

If you have some writeup/wiki/post about this, it would be greatly appreciated. Thank you again!

Best ~
