### ISSUE TITLE
Thoughts on Rails 6?

### ISSUE THREAD

**Issue by buffpojken** [wearefine/fae#478]
Rails 6 is now in rc1 - are there any thoughts on adding support?

**Comment by jamesmk** [comment]
We are working on our first Rails 6 app internally and support for it in Fae.

thanks

**Comment by michalkorzawski** [comment]
@jamesmk any update on this?

**Comment by jasonfine** [comment]
I added fae to a rails 6 rc1 app a couple months ago that has been in heavy development, so far no  issues. Going to update to the 6.0 release soon and see how things go, will keep you posted.

**Comment by michalkorzawski** [comment]
cool, thx!

**Comment by MirkoCindric** [comment]
Any eta on rails 6 support?

**Comment by liaden** [comment]
Just trying out a demo (and using Rails 6), I had to add  `config.autoloader = :classic` to `config/application.rb` to get `rails g fae:install` to work.

**Comment by MirkoCindric** [comment]
Any update on rails 6 support

**Comment by richardsondx** [comment]
**To fix it for Rails 6:**

Update all the migrations files Fae generates so that the migration inherit from 
`ActiveRecord::Migration[6.0]` instead of `ActiveRecord::Migration`
For example:
`class CreateFaeRoles < ActiveRecord::Migration[6.0]`

Then run the migration: `rake db:migrate` and run Fae seed:
`rake fae:seed_db RAILS_ENV=<your_env>`

For more info on what happens behind the scene with `fae:install` refer to this document:
`https://github.com/wearefine/fae/blob/master/docs/installation/index.md`

👍 that should work

**Comment by diegoshakan** [comment]
> ### **To fix it for Rails 6:**
> You can find more info on what happens behind the scene with `fae:install` refer to this document:
> `https://github.com/wearefine/fae/blob/master/docs/installation/index.md`
> 
> To fix this we're going to do some manual updates.
> 
> **1. Update all the migrations files Fae generates**
> 
> All the migration should inherit from `ActiveRecord::Migration[6.0]` instead of `ActiveRecord::Migration`
> For example:
> `class CreateFaeRoles < ActiveRecord::Migration[6.0]`
> 
> **2. Run the migration**
> 
> `rake db:migrate`
> 
> **3. run Fae seed**
> 
> `rake fae:seed_db RAILS_ENV=<your_env>`
> 
> **4. Update manifest.js**
> 
> Add `//= link fae/application.css` to your manifest
> 
> **5. Tell rails to precompile fae/application.js**
> 
> Add the following line to assets.rb
> 
> `Rails.application.config.assets.precompile += %w( fae/application.js)`
> 
>  that should work

I try add just the line 4, but doesn't work. So I just add `//= link fae/application.js` below the line 4 and works to me. 
If anybody had the same problem, this is the solution.

**Comment by jamesmk** [comment]
I apologize for the lack of official Rails 6 support and appreciate the work arounds. Fae 3.0 is in active development current which will support Rails 7. We expect a release by end of year.
