### ISSUE TITLE
Webpacker and Asset Pipeline

### ISSUE THREAD

**Issue by Swan-Chris** [wearefine/fae#483]
Hi,

So I was trying to set up Fae in order to test it out on our app, however, we use Webpacker and have no asset pipeline, I've been unable to install fae properly, are you able to work with Webpacker and without the Asset Pipeline?

I've attached the error for reference.
![image](https://user-images.githubusercontent.com/37653383/60009492-43d74700-9676-11e9-922a-54ac201966c0.png)

Best regards,
Chris Swan

**Comment by jamesmk** [comment]
With the release of Fae 3 (#594) and Rails 7 support we have no plans to support Webpacker.
