### ISSUE TITLE
Allow update to devise 4.7.1

### ISSUE THREAD

**Issue by rdunlop** [wearefine/fae#512]
I would like to be able to update to devise 4.7.1, since there's a security issue in earlier versions, see https://github.com/plataformatec/devise/issues/5071.

Can we adjust the dependency for devise to allow for that version?

I recognize that some testing of this version is necessary to gain confidence that things work together....version 4.7.1 has been out for 2 months now, has that been enough time?

**Comment by jclemans** [comment]
I've had luck running Devise 4.7.3 as a dependency in Fae locally, so it looks like this is something we should be able to incorporate in the near future. If you want to run that version of Devise right now, you can fork Fae and change the version in the gemspec. You could also create a PR for the change and live that "#opensourcelife".
