### ISSUE TITLE
Allow update to simple_form 5.0.x

### ISSUE THREAD

**Issue by rdunlop** [wearefine/fae#513]
I would like to be able to upgrade simple_form to 5.0.x, since there's a security issue reported by https://github.com/plataformatec/simple_form/security/advisories/GHSA-r74q-gxcg-73hx.

It's possible that the `fae` usage of simple_form doesn't use this particular feature, but without knowing the internal details, I can't be sure, and also, my own project tooling alerts for security-warning-gems no matter whether we're susceptible or not.

Can we adjust the system to allow for `simple_form` 5?

**Comment by joshzandman** [comment]
Any update on this?

**Comment by jamesmk** [comment]
Fixed in #564 (v2.2)
