### ISSUE TITLE
Can not found fae:install rake

### ISSUE THREAD

**Issue by uxgnod** [wearefine/fae#530]
Hi, 
I add `gem 'fae-rails'` to my new Rails 5.2 project's Gemfile, and run `bundle install`
After that, I run `bundle exec rails fae:install`, there is not output and just stop there.
Then I list rake tasks, there is only `fae:install:migrations`

Can anyone help me find the problem?
![image](https://user-images.githubusercontent.com/20808486/81660581-8744ca80-946d-11ea-817c-6eae4c29a71c.png)

**Comment by jasonfine** [comment]
Hi can you please try

`rails g fae:install` - you're missing the `g` i think.

**Comment by uxgnod** [comment]
> Hi can you please try
> 
> `rails g fae:install` - you're missing the `g` i think.

Hi，Sorry I forget `g` in this issue, but I did input `g` with `bundle exec rails g fae:install` ， and after input that , it stoped and no output 🤣 
![image](https://user-images.githubusercontent.com/20808486/81758631-f9142700-94f4-11ea-8c23-89ed8453262a.png)
