### ISSUE TITLE
No image upload field after adding has_fae_image to the model

### ISSUE THREAD

**Issue by papebarka** [wearefine/fae#536]
I was testing out the CMS and tried to add image upload functionality.

1. After adding to the model **has_fae_image :product**

2. I added the form input in the view **fae_image_form f, :product, label: 'Product', required: true**

Every input field is showing correctly except the image upload which is not showing at all.

Whan can be done to solve this issue?

**Comment by jasonfine** [comment]
If you are adding a file uploader to an existing model, you have to manually add this to the controller in question that the scaffold generators would normally do for you upon initial creation:

```
private

def build_assets
  @item.build_product if @item.product.blank?
end

**Comment by papebarka** [comment]
I was previously doing that but it was not working for reasons I ignore. I started from scratch again and now it works fine.
Thanks :) !
