### ISSUE TITLE
Slugger for multilingual slugs?

### ISSUE THREAD

**Issue by EvanAgee** [wearefine/fae#539]
I've recently been updating a site to use Fae's multilingual features which went very well. One problem we're running into, however, is that some models support a multilingual slug (slug_en, slug_es, etc) but I'm not seeing any options in Slugger to handle this. 

Any advice?

**Comment by jamesmk** [comment]
There isn't a way in Fae to do this out of the box. You options would be to add your own slugging feature via custom JS in `fae.js` or to add a feature to Fae that would allow an optional slug target. 

My initial thought would be something like
```
= fae_input f, :title_es, input_class: 'slugger_es'
= fae_input f, :slug_es, slugger_class: 'slugger_es'
```

Full transparency, we won't likely be working on this feature. All multilingual sites we've done with Fae have used common slugs with an embedded locale in the path. Though, I'd happily accept a PR for this feature.

thanks
