### ISSUE TITLE
Rails 7 

### ISSUE THREAD

**Issue by mountaindog** [wearefine/fae#581]
Greetings,
Not necessarily an issue; currently exploring CMS packages/engines/gems for an upcoming Rails 7 project. I don't see any documentation that it will run with Rails 7 or 6, for that matter. Just curious. A decent CMS engine is getting hard to find for Rails these days.

**Comment by jasonfine** [comment]
Hey, thanks for reaching out, we're actually really close to rolling out Rails 7 support. Should be within the next couple of weeks if everything stays on schedule!

**Comment by kimili** [comment]
Any update on this? I'm trying to upgrade an older installation for a client so they can be up-to-date on their Heroku install, but because we're using Fae 2.2, we're still stuck on Rails 5/Ruby 2.7, thus a deprecated Heroku stack.

**Comment by jasonfine** [comment]
Going to be a few more weeks, but this is definitely happening. The 3.0 release will be using Rails 7/Ruby 3 by default.

**Comment by sunto** [comment]
@jasonfine - wanted to see if there is any way we can help.  Definitely interested in seeing this go to rails 7.

**Comment by laurahelms** [comment]
@jasonfine We are currently unable to upgrade our Heroku stack until FAE is on Rails 7. Heroku-18 will reach EOL in the next couple months and will mean that we can no longer build or deploy changes to our applications using FAE. Can you please provide an update for the release of this work?
